import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {transform} from 'esbuild';
import {createApplication} from '../server/app.mjs';
import {readConfig} from '../server/config.mjs';

const out=process.env.EVIDENCE_DIR||'artifacts/cloud-v1';await mkdir(out,{recursive:true});
const dir=await mkdtemp(join(tmpdir(),'mario-cloud-browser-'));
let clock=Date.now();
const config=readConfig({PUBLIC_ORIGIN:'http://127.0.0.1:5173',DEV_AUTH_ENABLED:'true',DATABASE_PATH:join(dir,'race.sqlite')});
const app=createApplication({config,now:()=>clock});
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
config.origin=`http://127.0.0.1:${app.server.address().port}`;config.apiOrigin=config.appOrigin=config.origin;
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const checks=[],errors=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',error=>errors.push(error.message));
 await page.goto(config.origin);await page.locator('#loading').waitFor({state:'detached'});
 await page.getByRole('button',{name:'用户登录与云端排行榜'}).click();
 assert.equal(await page.locator('.cloud-email').count(),1);
 assert.equal(await page.locator('.cloud-email input:disabled').count(),2);
 await page.getByLabel('本地开发测试（非邮箱 / Google 登录）').fill('云端验证车手');
 await page.getByRole('button',{name:'测试登录',exact:true}).click();
 await page.getByRole('heading',{name:'云端验证车手',exact:true}).waitFor();
 const cookies=await page.context().cookies();assert(cookies.some(c=>c.name==='mario_session'&&c.httpOnly&&c.sameSite==='Lax'));
 checks.push('real game login and HttpOnly session cookie');
 await page.screenshot({path:`${out}/desktop-account-empty.png`});
 await page.getByRole('button',{name:'关闭排行榜'}).click();
 await page.locator('#fullscreen').click();
 await page.getByRole('button',{name:'用户登录与云端排行榜'}).click();
 assert.equal(await page.locator('.cloud-dialog').evaluate(el=>document.fullscreenElement?.contains(el)),true);
 await page.getByRole('button',{name:'关闭排行榜'}).click();
 await page.locator('#fullscreen').click();checks.push('account dialog remains inside fullscreen game');
 const ticketResponse=page.waitForResponse(r=>r.url().endsWith('/api/races')&&r.request().method()==='POST');
 await page.locator('#start').click();assert.equal((await ticketResponse).status(),201);
 await page.getByRole('button',{name:'用户登录与云端排行榜'}).click();
 await page.getByRole('button',{name:'关闭排行榜'}).click();
 assert.equal(await page.locator('#dialog-title').textContent(),'稍作休息');checks.push('starting a real race issues ticket; account dialog pauses gameplay');
 // Exercise the exact UI module against the real HTTP service, with a controllable race clock.
 const source=(await readFile('src/cloud.ts','utf8')).replace("import './cloud.css';",'');
 const module=(await transform(source,{loader:'ts',format:'esm'})).code;
 const css=await readFile('src/cloud.css','utf8');
 await page.route('**/__cloud-module.js',route=>route.fulfill({contentType:'text/javascript',body:module}));
 await page.route('**/__cloud-harness',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh"><head><meta charset="utf-8"><style>${css}</style></head><body><div id="app"><nav class="toolbar"></nav><div id="result"></div></div><script type="module">import {mountCloud} from '/__cloud-module.js';window.harness=mountCloud({onOpen(){},isTest:false});</script></body></html>`}));
 await page.goto(`${config.origin}/__cloud-harness`);await page.locator('.cloud-trigger.signed-in').waitFor();
 const started=page.waitForResponse(r=>r.url().endsWith('/api/races')&&r.status()===201);await page.evaluate(()=>window.harness.startRace('peach'));await started;
 clock+=65000;
 let failed=false;
 await page.route('**/api/races/*/finish',async route=>{if(!failed){failed=true;await route.abort('failed');}else await route.continue();});
 await page.evaluate(()=>window.harness.finishRace({timeMs:62000,character:'peach',position:2,coins:7}));
 await page.getByRole('button',{name:'重试保存'}).click();
 await page.getByText('已保存到标准道具竞速榜 · 全球第 1 名 · 最佳 01:02.000',{exact:true}).waitFor();
 assert.equal(app.db.prepare('SELECT COUNT(*) n FROM races WHERE finished_at IS NOT NULL').get().n,1);
 checks.push('real score upload failure/retry stores exactly one completed race');
 await page.getByRole('button',{name:'查看排行榜 →'}).click();await page.locator('.cloud-rank-you').waitFor();
 assert.match(await page.locator('.cloud-rank-you').innerText(),/云端验证车手 · 你/);
 assert.match(await page.locator('.cloud-rank-you').innerText(),/碧姬/);
 checks.push('personal best, rank, character and own-user highlight read back from SQLite');
 await page.getByRole('button',{name:'关闭排行榜'}).click();
 const trialStarted=page.waitForResponse(r=>r.url().endsWith('/api/races')&&r.status()===201);
 await page.evaluate(()=>window.harness.startRace('peach','time-trial'));await trialStarted;
 await page.evaluate(()=>window.harness.setMode('grand-prix'));clock+=65000;
 await page.evaluate(()=>window.harness.finishRace({timeMs:57000,character:'peach',position:1,coins:7}));
 await page.getByText('已保存到计时挑战榜 · 全球第 1 名 · 最佳 00:57.000',{exact:true}).waitFor();
 await page.getByRole('button',{name:'查看排行榜 →'}).click();await page.locator('.cloud-rank-time').filter({hasText:'00:57.000'}).waitFor();
 await page.getByRole('button',{name:'标准道具竞速榜',exact:true}).click();await page.locator('.cloud-rank-time').filter({hasText:'01:02.000'}).waitFor();
 await page.getByRole('button',{name:'计时挑战榜',exact:true}).click();await page.locator('.cloud-rank-time').filter({hasText:'00:57.000'}).waitFor();
 assert.equal(app.db.prepare('SELECT COUNT(*) n FROM races WHERE finished_at IS NOT NULL').get().n,2);
 checks.push('trial ticket survives board switches and saves to separate trial statistics/leaderboard');
 await page.getByRole('button',{name:'关闭排行榜'}).click();
 const casualStarted=page.waitForResponse(r=>r.url().endsWith('/api/races')&&r.status()===201);
 await page.evaluate(()=>window.harness.startRace('peach','grand-prix','casual'));await casualStarted;clock+=65000;
 await page.evaluate(()=>window.harness.finishRace({timeMs:54000,character:'peach',position:1,coins:7}));
 await page.getByText('已保存休闲成绩与每日成长 · 不计入标准竞速排名',{exact:true}).waitFor();
 const casual=app.db.prepare("SELECT difficulty FROM races WHERE finished_at IS NOT NULL ORDER BY finished_at DESC LIMIT 1").get();assert.equal(casual.difficulty,'casual');
 await page.getByRole('button',{name:'查看排行榜 →'}).click();await page.getByRole('button',{name:'标准道具竞速榜',exact:true}).click();await page.locator('.cloud-rank-time').filter({hasText:'01:02.000'}).waitFor();
 checks.push('casual result confirms saved growth without a rank, and leaves standard best unchanged');


 await page.goto(config.origin);await page.locator('#loading').waitFor({state:'detached'});
 await page.getByRole('button',{name:'用户登录与云端排行榜'}).click();await page.locator('.cloud-rank-you').waitFor();
 await page.screenshot({path:`${out}/desktop-account-saved.png`});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/mobile-account-saved.png`});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await page.locator('.cloud-dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);
 checks.push('reload retains signed-in identity and best score; mobile dialog has no horizontal overflow');
 await page.getByRole('button',{name:'退出登录',exact:true}).click();await page.getByRole('heading',{name:'游客车手',exact:true}).waitFor();
 assert.equal((await (await page.request.get(`${config.origin}/api/me`)).json()).user,null);
 checks.push('logout invalidates server session');
 await page.goto(`${config.origin}/?test=1`);await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__);
 await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.setState('finished'));
 await page.getByText('测试模式 · 成绩不上传',{exact:true}).waitFor();
 assert.equal(app.db.prepare('SELECT COUNT(*) n FROM races WHERE finished_at IS NOT NULL').get().n,3);
 checks.push('game QA finish hooks never upload synthetic scores');
 assert.deepEqual(errors,[]);
 const report={passed:true,checks,errors,realOAuth:'not exercised; credentials required',deployment:'local HTTP and SQLite; no Alibaba server supplied'};
 await writeFile(`${out}/browser.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});}
