import assert from 'node:assert/strict';
import * as THREE from 'three';
import {KartDriving} from '../src/driving.ts';
const barrier={a:{x:-12,z:110},b:{x:12,z:110},radius:.2,kind:'rail'};
const track={trackLength:1000,colliders:[barrier],sample(t,lane=0){return {position:new THREE.Vector3(lane,.14,t*1000),tangent:new THREE.Vector3(0,0,1),normal:new THREE.Vector3(1,0,0)};}};
const d=new KartDriving(track);d.reset(.1,0,40);
for(let f=0;f<30;f++)d.step({throttle:true,brake:false,steer:0,hop:false},0,1/60);
console.log({barrierZ:110,kartZ:d.position.z,speed:d.speed});
assert(d.position.z<108.5,'kart must stop on near side of visible guardrail instead of passing through');
assert(d.speed<25,'head-on guardrail collision must reduce speed');
console.log('guardrail collision passed');
const checks=['guardrail blocks and slows kart'];
const noInput={throttle:true,brake:false,steer:0,hop:false};
d.reset(.1,0,65);d.boost=2;for(let i=0;i<30;i++)d.step(noInput,0,1/60);assert(d.position.z<108.5);assert.equal(d.boost,0);checks.push('boosted impact cannot cross wall or preserve boost');
d.reset(.12,0,-10);for(let i=0;i<90;i++)d.step({throttle:false,brake:true,steer:0,hop:false},0,1/60);assert(d.position.z>111.5);checks.push('reverse impact blocks opposite side');
const {moveCircle,sweepCircle}=await import('../src/collision.ts');
const long={a:{x:0,z:-30},b:{x:0,z:30},radius:.2,kind:'rail'};
let result=moveCircle({x:-5,z:-5},{x:40,z:40},.3,1.6,[long]);assert(result.position.x< -1.79);assert(result.position.z>5);checks.push('glancing impact retains movement along barrier');
result=moveCircle({x:-100,z:0},{x:1000,z:0},.3,1.6,[long]);assert(result.position.x< -1.79);checks.push('swept collision prevents high-speed tunnelling');
result=moveCircle({x:-.2,z:0},{x:0,z:0},0,1.6,[long]);assert(result.position.x< -1.79);checks.push('overlap correction runs even without movement');
assert(sweepCircle({x:-5,z:31},{x:10,z:0},1.6,[long]));assert.equal(sweepCircle({x:-5,z:34},{x:10,z:0},1.6,[long]),null);checks.push('rounded rail tips collide while real gaps remain open');
const prop={a:{x:0,z:0},b:{x:0,z:0},radius:1,kind:'prop'};result=moveCircle({x:-10,z:0},{x:60,z:0},.4,1.6,[prop]);assert(result.position.x< -2.59);checks.push('tree and post circular proxies block vehicles');
console.log(JSON.stringify({passed:true,checks},null,2));
