import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/combat-v1';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);const combat=()=>hook('combat');
const setup=async arg=>{for(const key of ['KeyE','KeyQ','KeyW','KeyA','KeyD'])await page.keyboard.up(key);await hook('setupCombat',arg);await page.waitForTimeout(80);};
try{
 await page.goto('http://localhost:5173/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);await page.screenshot({path:out+'/difficulty-menu.png'});
 await hook('aiAtBox');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().stats.collected>0);assert((await combat()).ai.some(a=>a.inventory.some(s=>s.pending)));checks.push('AI physically collects a real box into its own roulette');
 await setup();await hook('giveItem','green-shell');await page.keyboard.press('KeyE');await page.waitForTimeout(50);assert.equal((await combat()).projectiles.filter(p=>p.owner==='mario').length,1);assert.equal((await read()).item,null);checks.push('quick E press launches exactly one shell');
 await setup();await hook('giveItem','green-shell');await hook('addReserve','banana');await page.keyboard.down('KeyE');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held==='green-shell');assert.equal((await combat()).projectiles.length,0);
 await hook('attack',{kind:'red-shell'});await page.locator('#incoming-warning').filter({hasText:'红龟壳'}).waitFor();await page.screenshot({path:out+'/rear-defense-warning.png'});await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().stats.blocks===1);assert.equal((await combat()).stats.playerHits,0);assert.equal((await read()).item,'banana');await page.keyboard.up('KeyE');await page.waitForTimeout(70);assert.equal((await read()).item,'banana');assert.equal((await combat()).projectiles.filter(p=>p.owner==='mario').length,0);checks.push('rear red shell warns then is intercepted; only held slot consumed, reserve never auto-fires');
 await setup({behind:false,distance:12});await hook('giveItem','banana');await page.keyboard.down('KeyE');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held==='banana');await hook('placeHazard','green-shell');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().stats.playerHits===1);assert.equal((await combat()).stats.blocks,0);assert((await combat()).protection>2);await page.keyboard.up('KeyE');checks.push('front hit cannot be blocked by a rear item and grants a recovery window');
 await setup();await hook('giveItem','red-shell');await page.keyboard.down('KeyE');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held!==null);await page.keyboard.press('Escape');assert.equal((await combat()).held,null);await page.keyboard.up('KeyE');await page.click('#resume');await page.waitForTimeout(100);assert.equal((await read()).item,'red-shell');assert.equal((await combat()).projectiles.length,0);checks.push('pause cancels hold without throwing or consuming inventory');
 await setup();await hook('giveItem','banana');const button=await page.locator('#item').boundingBox();await page.mouse.move(button.x+button.width/2,button.y+button.height/2);await page.mouse.down();await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held==='banana');await page.locator('#item').dispatchEvent('pointercancel');await page.mouse.up();await page.waitForTimeout(50);assert.equal((await combat()).held,null);assert.equal((await read()).item,'banana');assert.equal((await combat()).projectiles.length,0);checks.push('touch/pointer cancellation preserves held inventory without a shot');
 await setup();await hook('giveItem','green-shell');await page.evaluate(()=>{window.padButtons=Array.from({length:17},()=>({pressed:false,value:0}));window.padButtons[4]={pressed:true,value:1};window.padConnected=true;Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>window.padConnected?[{id:'Xbox',mapping:'standard',connected:true,axes:[0,0],buttons:window.padButtons}]:[]});});await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held!==null);await page.keyboard.press('Escape');await page.click('#resume');await page.waitForTimeout(350);assert.equal((await combat()).held,null);await page.evaluate(()=>window.padButtons[4]={pressed:false,value:0});await page.waitForTimeout(100);assert.equal((await combat()).projectiles.length,0);await page.evaluate(()=>window.padButtons[4]={pressed:true,value:1});await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held!==null);await page.evaluate(()=>window.padConnected=false);await page.waitForTimeout(100);assert.equal((await combat()).held,null);assert.equal((await read()).item,'green-shell');assert.equal((await combat()).projectiles.length,0);checks.push('held gamepad button waits for release after pause; disconnect cancels without shooting');
 for(const kind of ['mushroom','red-shell','green-shell','banana']){await setup({behind:kind!=='banana',distance:kind==='green-shell'?24:50,t:kind==='green-shell'?.78:.42,lane:kind==='green-shell'?0:-3});await hook('armAi',kind);await page.waitForFunction(kind=>{const c=window.__THREE_GAME_TEST_HOOKS__.combat();return kind==='mushroom'?c.ai.find(a=>a.id==='luigi').boost>0:c.projectiles.some(p=>p.kind===kind&&p.owner==='luigi');},kind,{timeout:10000});const c=await combat();assert(kind==='mushroom'?c.ai.some(a=>a.boost>0):c.projectiles.some(p=>p.kind===kind&&p.owner!=='mario'),`${kind}: ${JSON.stringify(c)}`);}
 checks.push('AI executes all four real item effects via strategy decisions');
 await hook('setState','ready');await hook('selectDifficulty','casual');await hook('selectRaceMode','time-trial');await hook('setupCourse',{id:'garden',u:.51,lane:2.4,time:5.2});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.course.hits===1);assert((await read()).player.immune<=1.65);assert.equal((await combat()).stats.used,0);assert((await hook('pickups')).filter(p=>p.kind==='item').every(p=>!p.visible));checks.push('casual selection cannot change time-trial hazard immunity or enable AI items');
 await hook('setState','ready');await hook('selectRaceMode','grand-prix');await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/mobile-menu.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await setup();await hook('giveItem','banana');const mobileButton=await page.locator('#item').boundingBox();await page.mouse.move(mobileButton.x+mobileButton.width/2,mobileButton.y+mobileButton.height/2);await page.mouse.down();await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.combat().held==='banana');await hook('attack',{kind:'red-shell'});await page.locator('#incoming-warning').filter({hasText:'红龟壳'}).waitFor();await page.screenshot({path:out+'/mobile-defense.png'});await page.mouse.up();await page.waitForTimeout(50);assert.equal((await read()).item,null);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('mobile difficulty and warning fit; long touch holds and release throws');
 assert.deepEqual(errors,[]);await fs.writeFile(out+'/browser.json',JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}catch(error){await fs.writeFile(out+'/failure.json',JSON.stringify({checks,errors,diagnostics:await read(),combat:await combat()},null,2));await page.screenshot({path:out+'/failure.png'});throw error;}finally{await browser.close();}
