import assert from 'node:assert/strict';import * as THREE from 'three';import {KartDriving} from '../src/driving.ts';
const track={trackLength:1000,sample(t,lane=0){const a=t*Math.PI*2,R=1000/(Math.PI*2);const tangent=new THREE.Vector3(-Math.sin(a),0,Math.cos(a)),normal=new THREE.Vector3(tangent.z,0,-tangent.x);return {position:new THREE.Vector3(Math.cos(a)*R,.14,Math.sin(a)*R).addScaledVector(normal,lane),tangent,normal};}};
const idle={throttle:false,brake:false,steer:0,hop:false};const checks=[],failures=[];
function test(name,fn){try{fn();checks.push(name);}catch(e){failures.push({name,error:e.message});}}
test('roadside crossing does not miss checkpoint',()=>{const d=new KartDriving(track);d.reset(.124,13,20,1);d.position.copy(track.sample(.126,13).position);d.project();assert.equal(d.nextGate,2);});
test('missing a checkpoint never teleports a kart already on the road',()=>{const d=new KartDriving(track);d.reset(.2,0,0,1);const before=d.position.clone();let rescued=false;for(let f=0;f<180;f++){d.step(idle,0,1/60);rescued||=d.recovered;}assert(!rescued);assert(d.position.distanceTo(before)<.01);assert.equal(d.nextGate,1,'skipped gate remains uncredited');});
test('recoverable grass detour does not force a reset',()=>{const d=new KartDriving(track);d.reset(.2,30,0,2);let rescued=false;for(let f=0;f<180;f++){d.step(idle,0,1/60);rescued||=d.recovered;}assert(!rescued);assert(Math.abs(d.lane-30)<.1);});
test('far stationary kart receives warning before rescue and preserves gates',()=>{const d=new KartDriving(track);d.reset(.2,80,0,2);let rescued=false;for(let f=0;f<120;f++){d.step(idle,0,1/60);rescued||=d.recovered;}assert(!rescued);assert(d.recoverySeconds>0);for(let f=0;f<90;f++){d.step(idle,0,1/60);rescued||=d.recovered;}assert(rescued);assert.equal(d.nextGate,2);assert(d.roadDistance<1);});
test('driving back toward track cancels pending rescue',()=>{const d=new KartDriving(track);d.reset(.2,80,0,2);for(let f=0;f<120;f++)d.step(idle,0,1/60);assert(d.recoverySeconds>0);const normal=track.sample(.2).normal;d.heading=d.travelHeading=Math.atan2(-normal.x,-normal.z);let rescued=false;for(let f=0;f<240;f++){d.step({...idle,throttle:true},0,1/60);rescued||=d.recovered;}assert(!rescued);assert.equal(d.recoverySeconds,0);assert(d.roadDistance<20);});
test('large checkpoint shortcut cannot award lap or trigger teleport',()=>{const d=new KartDriving(track);d.reset(.12,0,0,1);d.position.copy(track.sample(.9).position);d.project();assert.equal(d.nextGate,1);assert(!d.finished);});
console.log(JSON.stringify({passed:!failures.length,checks,failures},null,2));assert.equal(failures.length,0);
