import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/continuity-v4';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const checks=[],errors=[];let page;const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
const reset=async()=>{for(const k of ['KeyW','KeyA','KeyD','KeyC'])await page.keyboard.up(k);const f=(await read()).frame;await hook('setState','active-play');await page.waitForFunction(f=>window.__THREE_GAME_DIAGNOSTICS__.frame>f,f);};
try{page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:5173/?test=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>5);await reset();const observations=[];
for(let meters=6;meters>=-25;meters--){const key=await hook('setupOvertake',meters);const rival=(await hook('racerPositions')).find(r=>r.key===key);observations.push({meters,visible:rival.visible});if(meters===-4)await page.screenshot({path:`${out}/overtaken.png`});}
assert(observations.every(r=>r.visible),'overtaken opponents must stay in the scene across rear distance thresholds');checks.push('opponent stays visible across all 32 front-to-rear overtake positions');
await hook('setupOvertake',-8);await hook('setPausedForScreenshot',false);await page.keyboard.down('KeyC');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.lookBack);await page.waitForTimeout(200);assert((await hook('racerPositions')).every(r=>r.visible));await page.screenshot({path:`${out}/overtake-rear-view.png`});await page.keyboard.up('KeyC');checks.push('rear-view keeps overtaken opponents visible');
for(const kind of ['missed','grass']){await reset();await hook('setupDetour',kind);await page.waitForTimeout(80);const initial=await read();await page.waitForFunction(t=>window.__THREE_GAME_DIAGNOSTICS__.raceTime>=t+2.1,initial.raceTime);const final=await read();assert.equal(final.player.recoveryFlash,0);assert.equal(final.player.recoverySeconds,0);assert(Math.hypot(final.player.x-initial.player.x,final.player.z-initial.player.z)<.1);if(kind==='missed'){assert(final.player.checkpointMissed);assert.equal(final.player.nextGate,1);}await page.screenshot({path:`${out}/${kind}-no-reset.png`});}
checks.push('missing checkpoint on-road and a 30m grass detour do not teleport the player');
await reset();await hook('setupDetour','far');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.player.recoverySeconds>0);const gate=(await read()).player.nextGate;await page.waitForFunction(()=>document.querySelector('#driving-status').textContent.includes('秒后救援'));await page.screenshot({path:`${out}/rescue-warning.png`});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.player.recoveryFlash>0);assert.equal((await read()).player.nextGate,gate);checks.push('genuine far-off-track rescue is announced and preserves checkpoint progress');
await page.setViewportSize({width:390,height:664});await reset();await hook('setupOvertake',-4);await page.screenshot({path:`${out}/mobile-overtaken.png`});assert((await hook('racerPositions')).every(r=>r.visible));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('mobile chase view retains opponents without layout overflow');assert.deepEqual(errors,[]);
const report={passed:true,checks,observations,errors};await fs.writeFile(`${out}/continuity.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
