import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs/promises';
const out='artifacts/elimination-v1';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__),state=()=>hook('eliminationState');
async function start(){await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');}
try{
  await page.goto('http://localhost:5173/?test=1&v=elimination-v1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>2);
  await page.click('#elimination-select');assert.equal(await page.getAttribute('#elimination-select','aria-pressed'),'true');
  assert.match(await page.locator('#race-mode-note').textContent(),/第30秒首次淘汰/);assert.equal((await state()).lapLimit,null);
  await page.click('[data-driver=peach]');await page.click('[data-combat-difficulty=casual]');
  await page.screenshot({path:out+'/menu.png'});await start();
  assert.equal((await read()).player.driver,'peach');assert.equal((await hook('combat')).difficulty,'casual');assert.equal((await state()).state.activeIds.length,6);
  await hook('eliminationFixture',{time:25,playerLast:true});
  assert.equal(await page.getAttribute('#elimination-hud','data-danger'),'true');assert.equal(await page.getAttribute('#elimination-hud','data-warning'),'true');
  assert.equal(await page.locator('.elimination-seconds').textContent(),'5');assert.equal(await page.locator('.lap-cluster').isVisible(),false);
  await page.screenshot({path:out+'/danger-desktop.png'});
  await page.keyboard.press('Escape');const paused=(await state()).state;await page.waitForTimeout(250);assert.deepEqual((await state()).state,paused);
  await page.click('#resume');assert.equal((await state()).state.remaining,5);
  checks.push('menu preserves character/difficulty; warmup and last-five-second warning; pause freezes deadline');
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/danger-mobile.png'});
  let hud=await page.locator('#elimination-hud').boundingBox(),clock=await page.locator('.race-clock').boundingBox();assert(hud.x+hud.width<clock.x);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.setViewportSize({width:844,height:390});await page.screenshot({path:out+'/danger-landscape.png'});
  hud=await page.locator('#elimination-hud').boundingBox();clock=await page.locator('.race-clock').boundingBox();assert(hud.x+hud.width<clock.x);
  await hook('eliminationTick',30);const lost=await state();assert(lost.state.complete);assert.equal(lost.state.playerPlace,6);assert.equal(lost.state.elapsed,30);
  assert.equal(await page.locator('.elimination-survivors').count(),1);assert.equal(await page.locator('.elimination-timeline li').count(),1);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/loss-mobile.png'});
  await page.locator('#resume').scrollIntoViewIfNeeded();await page.click('#resume');await hook('setPausedForScreenshot',false);
  await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');assert.equal((await state()).state.activeIds.length,6);assert.equal((await state()).state.eliminated.length,0);
  checks.push('mobile/landscape HUD avoids clock; player elimination ends immediately at30s with no invented survivor ranks; retry restores all racers');
  await page.setViewportSize({width:1440,height:900});await hook('eliminationFixture',{time:29,progress:1.6});const dropped=await hook('eliminationThreat');
  assert((await hook('combat')).projectiles.some(p=>p.owner===dropped));assert((await hook('combat')).projectiles.some(p=>p.target===dropped));
  await hook('eliminationTick',30);let after=await state();assert.equal(after.state.activeIds.length,5);assert(!after.state.order.includes(dropped));
  assert(!(await hook('combat')).projectiles.some(p=>p.owner===dropped||p.target===dropped));assert(!after.badges.includes(dropped));assert.equal(after.racers.find(r=>r.id===dropped).speed,0);
  await page.screenshot({path:out+'/elimination-feedback.png'});await hook('eliminationTick',30.8);assert.equal((await state()).racers.find(r=>r.id===dropped).visible,false);
  await hook('eliminationCollision');const hits=(await read()).interactions.kartHits;await hook('setPausedForScreenshot',false);await page.waitForTimeout(150);await hook('setPausedForScreenshot',true);assert.equal((await read()).interactions.kartHits,hits);
  checks.push('eliminated AI exits ranking, item inventory, projectiles, badge and collision immediately, then visibly retreats');
  await hook('eliminationFixture',{time:49.9,progress:3.2});await hook('setPausedForScreenshot',false);await page.waitForTimeout(200);await hook('setPausedForScreenshot',true);
  assert.equal((await read()).mode,'racing');assert((await read()).lap>=4);assert.equal((await state()).state.activeIds.length,4);
  for(const [time,progress] of [[70,3.7],[90,4.7],[110,5.7]])await hook('eliminationFixture',{time,progress});
  const winner=await state();assert(winner.state.complete);assert.equal(winner.state.playerPlace,1);assert.equal(winner.state.winnerId,'peach');assert.deepEqual(winner.state.eliminated.map(e=>e.at),[30,50,70,90,110]);
  assert.equal(await page.locator('.elimination-timeline li').count(),5);assert.equal(await page.locator('.elimination-survivors').count(),0);await page.screenshot({path:out+'/winner-desktop.png'});
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('mushroom-elimination-v3-light-casual-qa')));assert.equal(saved.bestPlace,1);assert.equal(saved.last.survival,110);
  checks.push('fourth and later laps continue; five deadlines yield one champion at110s; local elimination record remains separate');
  await page.click('#home');await hook('setPausedForScreenshot',false);await page.click('[data-race-mode=time-trial]');assert.equal((await state()).selected,false);assert.equal((await state()).lapLimit,3);assert.equal(await page.locator('#elimination-hud').isVisible(),false);await start();
  assert.equal((await hook('racerPositions')).filter(r=>r.key!=='peach'&&r.visible).length,0);await hook('setState','near-finish');await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='finished');await page.keyboard.up('KeyW');assert.match(await page.locator('#dialog-eyebrow').textContent(),/TIME TRIAL/);
  await page.click('#home');await page.click('#cup-select');await start();assert.equal((await state()).lapLimit,3);assert.equal((await hook('cup')).state.rounds.length,0);assert.equal((await state()).selected,false);
  checks.push('exit restores normal three-lap time trial, ghost rules and cup mode');
  await page.keyboard.press('Escape');await page.click('#home');await page.click('#elimination-select');await start();
  await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new DOMException('blocked','QuotaExceededError');};});await hook('eliminationFixture',{time:30,playerLast:true});
  assert.match(await page.locator('.elimination-storage-warning').textContent(),/未保存/);await page.locator('#resume').click();assert.equal((await state()).state.eliminated.length,0);
  checks.push('unavailable local storage shows feedback and still permits retry');assert.deepEqual(errors,[]);
  await fs.writeFile(out+'/browser.json',JSON.stringify({passed:true,checks,lost,winner,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({checks,errors,state:await state(),last:await read()},null,2));await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
