import { chromium } from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
try {const page=await browser.newPage();await page.goto('http://127.0.0.1:5173/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__);const checks=[];
for(const [id,accelerator,brake] of [['Nintendo Switch Pro Controller',1,0],['Xbox Controller',0,1]]){
await page.evaluate(id=>{window.__pad={id,connected:true,mapping:'standard',buttons:Array.from({length:17},()=>({pressed:false,value:0})),axes:[0,0,0,0]};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.__pad]});window.__THREE_GAME_TEST_HOOKS__.setState('straight');},id);
await page.evaluate(n=>window.__pad.buttons[n].pressed=true,accelerator);await page.waitForTimeout(400);assert((await page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__.player.speed))>35);checks.push(`${id}: A accelerates`);
await page.evaluate(({accelerator,brake})=>{window.__pad.buttons[accelerator].pressed=false;window.__pad.buttons[brake].pressed=true;},{accelerator,brake});await page.waitForTimeout(1200);assert((await page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__.player.speed))<0);checks.push(`${id}: B brakes then reverses`);
await page.evaluate(()=>{window.__pad.buttons.forEach(b=>b.pressed=false);window.__THREE_GAME_TEST_HOOKS__.setState('ready');});await page.click('.garage-help');await page.evaluate(()=>window.__pad.buttons[9].pressed=true);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__.mode),'ready');await page.evaluate(()=>window.__pad.buttons[9].pressed=false);await page.keyboard.press('Escape');checks.push(`${id}: guide blocks gamepad start`);
}
const result={passed:true,method:'Injected browser standard Gamepad state, not physical hardware',checks};await fs.writeFile('artifacts/handling-v2/gamepad.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}finally{await browser.close();}
