import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const out='artifacts/interactions-v3';await fs.mkdir(out,{recursive:true});
const checks=[],errors=[];let page;
const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);
const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
const state=async()=>{for(const k of ['KeyW','KeyS','KeyA','KeyD','Space'])await page.keyboard.up(k);const previous=(await read()).frame;await hook('setState','straight');await page.waitForFunction(f=>window.__THREE_GAME_DIAGNOSTICS__.frame>f&&window.__THREE_GAME_DIAGNOSTICS__.mode==='racing',previous);};
const shot=async name=>{await hook('setPausedForScreenshot',true);await page.screenshot({path:`${out}/${name}.png`});await hook('setPausedForScreenshot',false);};
try{
page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:5173/?test=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>5);
await state();await hook('placeAtPickup','item');await page.keyboard.down('KeyW');await page.waitForTimeout(120);let d=await read();assert(d.rolling&&d.inventory.length===1,JSON.stringify({d,pickups:await hook('pickups'),errors}));assert(d.shards>0);assert(await page.locator('#item').evaluate(e=>e.classList.contains('rolling')));assert((await hook('pickups')).some(p=>p.kind==='item'&&!p.visible&&p.cooldown>0));await shot('item-shatter-roulette');const firstIcon=await page.getAttribute('#item','data-item');await page.waitForFunction(icon=>document.getElementById('item').dataset.item!==icon,firstIcon,{timeout:1200});checks.push('question box breaks into shards, disappears and starts visible icon roulette');
await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='paused');const pending=(await read()).inventory[0].remaining;await page.waitForTimeout(200);assert.equal((await read()).inventory[0].remaining,pending);await page.click('#resume');await page.keyboard.press('KeyE');assert.equal((await read()).item,null);await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.item!==null);await shot('item-awarded');checks.push('pause freezes roulette; first use press hurries without firing unseen item');
await page.keyboard.press('KeyE');await page.waitForTimeout(80);assert.equal((await read()).inventory.length,0);checks.push('awarded item can actually be used');
await state();await hook('giveItem','mushroom');await hook('placeAtPickup','item');await page.keyboard.down('KeyW');await page.waitForTimeout(120);d=await read();assert.equal(d.item,'mushroom');assert.equal(d.inventory.length,2);assert(d.inventory[1].pending);await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.inventory[1]?.item);const reserve=(await read()).inventory[1].item;await shot('two-items');await hook('placeAtPickup','item');await page.waitForTimeout(120);assert.equal((await read()).inventory.length,2);assert.equal((await read()).inventory[1].item,reserve);assert((await read()).shards>0);checks.push('second box fills backup slot; full inventory gives feedback without overwriting');
await page.keyboard.press('KeyE');await page.waitForTimeout(80);d=await read();assert.equal(d.item,reserve);assert(d.boost>0);checks.push('using front item promotes backup in order');await page.keyboard.up('KeyW');await page.waitForFunction(()=>{const p=window.__THREE_GAME_TEST_HOOKS__.pickups().find(p=>p.kind==='item');return p.visible&&p.cooldown===0;},null,{timeout:6000});checks.push('collected boxes visibly respawn');
for(const boosted of [false,true]){await state();const wall=await hook('placeAtBarrier',boosted);await page.keyboard.down('KeyW');await page.waitForTimeout(180);d=await read();const side=(d.player.x-wall.mid.x)*wall.normal.x+(d.player.z-wall.mid.z)*wall.normal.z;assert(d.interactions.railHits>0);assert(side>=1.6,`signed distance ${side}`);assert(d.player.speed<25);assert.equal(d.boost,0);await shot(boosted?'boost-wall-impact':'wall-impact');await page.waitForTimeout(350);d=await read();assert((d.player.x-wall.mid.x)*wall.normal.x+(d.player.z-wall.mid.z)*wall.normal.z>=1.6);
await hook('giveItem','green-shell');await page.keyboard.press('KeyE');await page.waitForTimeout(70);d=await read();assert(d.interactions.shellBounces>0);const shell=d.projectiles.find(p=>p.kind==='green-shell');assert(shell&&(shell.x-wall.mid.x)*wall.normal.x+(shell.z-wall.mid.z)*wall.normal.z>.9,'point-blank shell must spawn and reflect on near side');}
checks.push('normal and boosted head-on impacts remain on near side, lose speed and cancel boost');checks.push('point-blank shell launch cannot spawn beyond a guardrail');
await state();await hook('placeAtBarrier',false);await hook('giveItem','green-shell');await page.keyboard.press('KeyE');await page.waitForTimeout(100);assert((await read()).interactions.shellBounces>0);checks.push('green shell reflects from the same visible guardrail');
await state();const targetKey=await hook('setupRedChase');await page.keyboard.press('KeyE');let maxRoadDistance=0,targetHit=false;for(let i=0;i<38;i++){await page.waitForTimeout(80);const p=(await read()).projectiles.find(p=>p.kind==='red-shell');if(p)maxRoadDistance=Math.max(maxRoadDistance,p.roadDistance);if((await hook('racerPositions')).some(r=>r.key===targetKey&&r.hitTime>0)){targetHit=true;break;}}assert(targetHit,'red shell follows bend and reaches moving target');assert(maxRoadDistance<8.8,`red shell left road: ${maxRoadDistance}`);checks.push('red shell follows the curved road and hits its moving target');
await state();await hook('giveItem','mushroom');await page.keyboard.press('KeyE');await hook('placeAtBoost');await page.keyboard.down('KeyW');await page.waitForTimeout(100);assert((await read()).boost>1.7);checks.push('dash panel does not shorten mushroom boost');
for(const kind of ['banana','green-shell']){await state();await hook('setupCombat');await page.waitForTimeout(80);await hook('setCoins',5);await hook('giveItem','mushroom');await page.keyboard.press('KeyE');await hook('placeHazard',kind);await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.interactions.hits===1);d=await read();assert.equal(d.coins,2);assert(d.player.hitTime>0);assert.equal(d.boost,0);const yaw=d.player.modelYaw;await page.waitForTimeout(100);assert(Math.abs((await read()).player.modelYaw-yaw)>.2);await shot(`${kind}-hit`);await hook('placeHazard',kind);await page.waitForTimeout(180);assert.equal((await read()).interactions.hits,1);}
checks.push('banana and shell contact trigger visible spin/bounce, drop coins, cancel boost and protect against chained hits');
await state();await hook('placeRival');await page.keyboard.down('KeyW');await page.waitForTimeout(80);assert((await read()).interactions.kartHits>0);const positions=await hook('racerPositions');const separation=Math.hypot(positions[0].position[0]-positions[1].position[0],positions[0].position[2]-positions[1].position[2]);assert(separation>3.1,`racer separation ${separation}`);checks.push('close racers separate instead of staying overlapped during cooldown');
await state();await hook('placeAtPickup','item');await page.waitForTimeout(80);assert((await read()).rolling);await hook('setState','ready');await page.waitForTimeout(1600);d=await read();assert.equal(d.inventory.length,0);assert.equal(d.shards,0);checks.push('reset clears pending roulette and particle effects');
await page.setViewportSize({width:390,height:664});await state();await hook('giveItem','mushroom');await hook('placeAtPickup','item');await page.waitForTimeout(100);await shot('mobile-roulette');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const btn=await page.locator('#item').boundingBox(),backup=await page.locator('.item-reserve').boundingBox();assert(btn.x>=0&&backup.x>=0&&backup.x+backup.width<=390);await page.click('#item');await page.waitForTimeout(60);assert((await read()).boost>0);checks.push('mobile two-slot HUD fits and touch uses the front item');
assert.deepEqual(errors,[]);const report={passed:true,checks,errors};await fs.writeFile(`${out}/interactions.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
