import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs/promises';
const out='artifacts/loadouts-v1';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg}),read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__),loadout=()=>hook('loadout');
try{
 await page.goto('http://localhost:5173/?test=1&v=loadouts-v1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>2);await page.click('#loadout-open');assert.equal(await page.locator('[data-loadout]').count(),3);await page.screenshot({path:out+'/config-desktop.png'});
 await page.click('[data-loadout=speed]');assert.equal((await loadout()).handling.topSpeed,51);await page.keyboard.press('Enter');assert.equal((await read()).mode,'ready');await page.keyboard.press('Escape');assert.equal(await page.locator('#loadout-dialog').evaluate(d=>d.open),false);
 await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>2);assert.equal((await loadout()).selected,'speed');checks.push('three configurations are open; real handling changes; modal isolates driving keys; selection survives reload');
 await page.click('#loadout-open');await page.setViewportSize({width:390,height:844});await page.locator('[data-loadout=drift]').scrollIntoViewIfNeeded();await page.click('[data-loadout=drift]');assert.equal((await loadout()).handling.chargeRate,1.2);await page.screenshot({path:out+'/config-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:844,height:390});await page.screenshot({path:out+'/config-landscape.png'});await page.keyboard.press('Escape');await page.click('#cup-select');await page.click('#loadout-open');
 const before=await page.evaluate(()=>({...localStorage}));await page.locator('#loadout-test-drive').scrollIntoViewIfNeeded();await page.click('#loadout-test-drive');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');assert((await loadout()).testDrive);assert.equal(await page.locator('.trial-hud').isVisible(),false);assert.equal((await hook('racerPositions')).filter(r=>r.key!=='mario'&&r.visible).length,0);assert((await hook('pickups')).every(p=>!p.visible));
 await page.keyboard.down('KeyW');await page.waitForTimeout(600);await page.keyboard.up('KeyW');assert((await read()).player.speed>10);await page.keyboard.press('Escape');const paused=await read();await page.waitForTimeout(200);assert.equal((await read()).raceTime,paused.raceTime);await page.click('#resume');
 await hook('selectLoadout','light');assert.equal((await loadout()).selected,'drift');await hook('practiceNearEnd');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='finished');assert.match(await page.locator('#dialog-title').textContent(),/试驾完成/);assert.deepEqual(await page.evaluate(()=>({...localStorage})),before);await page.screenshot({path:out+'/practice-result.png'});
 await page.locator('#home').scrollIntoViewIfNeeded();await page.click('#home');assert.equal(await page.locator('#loadout-dialog').evaluate(d=>d.open),true);assert.equal((await hook('cup')).selected,true);assert.equal((await loadout()).testDrive,false);checks.push('mobile/landscape controls fit; real driving practice pauses, blocks profile changes, writes no records and returns to prior cup mode');
 await page.click('[data-loadout=speed]');await page.keyboard.press('Escape');await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');await hook('selectLoadout','light');assert.equal((await loadout()).selected,'speed');await hook('cupNearFinish');await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='finished');await page.keyboard.up('KeyW');await page.click('#resume');assert.equal((await loadout()).selected,'speed');assert.equal((await loadout()).handling.topSpeed,51);assert.equal((await read()).track,'castle');
 await page.keyboard.press('Escape');await page.click('#home');await page.click('[data-race-mode=time-trial]');await page.click('#loadout-open');await page.click('[data-loadout=light]');const lightKey=(await loadout()).ghostKey;await page.evaluate(key=>localStorage.setItem(key,JSON.stringify({version:1,rulesVersion:2,character:'mario',durationMs:60000,splits:Array.from({length:12},(_,i)=>(i+1)*5000),frames:Array.from({length:1201},(_,i)=>[i*50,i*.1,.14,0,0])})),lightKey);await hook('selectLoadout','light');assert.equal((await read()).trial.bestMs,60000);await page.click('[data-loadout=drift]');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.trial.bestMs===null);assert.notEqual((await loadout()).ghostKey,lightKey);await page.click('[data-loadout=light]');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.trial.bestMs===60000);checks.push('configuration stays locked across cup stations; ghosts and local records are separated by handling profile');
 await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new DOMException('blocked','QuotaExceededError');};});await page.click('[data-loadout=speed]');assert.equal((await loadout()).selected,'speed');await page.keyboard.press('Escape');assert.match(await page.locator('#toast').textContent(),/本次选择仍然有效/);await page.click('#elimination-select');await page.click('#start');assert.equal((await loadout()).handling.topSpeed,51);assert.equal((await hook('eliminationState')).lapLimit,null);checks.push('storage failure keeps session selection usable; elimination retains selected configuration and unlimited laps');
 assert.deepEqual(errors,[]);await fs.writeFile(out+'/browser.json',JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}catch(e){console.error(e);await fs.writeFile(out+'/failure.json',JSON.stringify({checks,errors,last:await read(),loadout:await loadout()},null,2));await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
