import assert from 'node:assert/strict';
import {dayKey,dailyTasks,emptyProgress,normalizeProgress,applyRace,snapshot,equipProgress,validateMetrics} from '../shared/progression.mjs';
const checks=[];
function check(name,fn){fn();checks.push(name);}
const days=Array.from({length:4},(_,i)=>`2026-09-${12+i}`);
const all={orangeDrifts:3,coinsCollected:10,rescues:0,shortcutClears:2};
const race={mode:'time-trial',metrics:all};
check('Beijing midnight rotates three distinct tasks and covers all six templates',()=>{assert.equal(dayKey(Date.parse('2026-09-12T15:59:59Z')),'2026-09-12');assert.equal(dayKey(Date.parse('2026-09-12T16:00:00Z')),'2026-09-13');const ids=new Set();for(const d of days){const tasks=dailyTasks(d);assert.equal(new Set(tasks.map(t=>t.id)).size,3);assert(tasks.some(t=>['finish','clean'].includes(t.id)));tasks.forEach(t=>ids.add(t.id));}assert.equal(ids.size,6);assert.equal(snapshot(emptyProgress(),days[0]).resetAt,Date.parse('2026-09-12T16:00:00Z'));});
check('each daily task awards once and repeating full races cannot farm daily XP',()=>{for(const d of days){let s=applyRace(emptyProgress(),race,d);assert.equal(s.xp,300);s=applyRace(s,race,d);assert.equal(s.xp,300);assert(snapshot(s,d).tasks.every(t=>t.complete));}});
check('coins require ten in ONE completed race, drift and exits accumulate across races',()=>{const d=days.find(d=>dailyTasks(d).some(t=>t.id==='coins'));let s=emptyProgress();for(let i=0;i<2;i++)s=applyRace(s,{mode:'grand-prix',metrics:{...all,coinsCollected:6,orangeDrifts:1}},d);const tasks=snapshot(s,d).tasks;assert.equal(tasks.find(t=>t.id==='coins').progress,6);assert.equal(tasks.find(t=>t.id==='coins').complete,false);const driftDay=days.find(d=>dailyTasks(d).some(t=>t.id==='drift'));let a=emptyProgress();for(let i=0;i<3;i++)a=applyRace(a,{mode:'grand-prix',metrics:{...all,orangeDrifts:1}},driftDay);assert(snapshot(a,driftDay).tasks.find(t=>t.id==='drift').complete);});
check('manual/automatic rescue invalidates clean objective and legacy missing metrics never assumes clean',()=>{const d=days.find(d=>dailyTasks(d).some(t=>t.id==='clean'));for(const metrics of [undefined,{...all,rescues:1}]){const s=applyRace(emptyProgress(),{mode:'grand-prix',metrics},d);assert.equal(snapshot(s,d).tasks.find(t=>t.id==='clean').progress,0);assert.equal(snapshot(s,d).tasks.find(t=>t.id==='trial').progress,0);}});
check('old-day race settles old tasks while current-day view starts empty',()=>{const s=applyRace(emptyProgress(),race,days[0]);assert.equal(s.xp,300);assert(snapshot(s,days[1]).tasks.every(t=>t.progress===0));assert.equal(applyRace(s,race,days[1]).xp,600);});
check('three reward thresholds enforce equipment and permit restoration',()=>{let s=emptyProgress();assert.throws(()=>equipProgress(s,{paint:'mint',trail:'standard',title:'rookie'}));s=applyRace(s,{mode:'grand-prix'},days.find(d=>dailyTasks(d).some(t=>t.id==='finish')));assert.equal(s.xp,100);s=equipProgress(s,{paint:'mint',trail:'standard',title:'rookie'});assert.throws(()=>equipProgress(s,{paint:'mint',trail:'violet',title:'rookie'}));s=applyRace(s,race,days[0]);s=applyRace(s,race,days[1]);s=equipProgress(s,{paint:'mint',trail:'violet',title:'star'});assert.equal(snapshot(s,days[1]).level,4);assert.equal(equipProgress(s,{paint:'standard',trail:'standard',title:'rookie'}).xp,s.xp);assert.throws(()=>equipProgress(s,{paint:'turbo',trail:'standard',title:'rookie'}));});
check('state round trips; malformed, inconsistent or incompatible records safely reset',()=>{const s=applyRace(emptyProgress(),race,days[0]);assert.deepEqual(normalizeProgress(JSON.parse(JSON.stringify(s))),s);for(const bad of [null,{version:2}, {...s,xp:999999},{...s,days:{bad:{}}},{...s,days:{'2026-02-31':{}}}])assert.equal(normalizeProgress(bad).xp,0);});
check('invalid metrics are rejected, no input state mutation',()=>{for(const bad of [null,{}, {...all,rescues:-1},{...all,orangeDrifts:1.5},{...all,shortcutClears:7}])assert.throws(()=>validateMetrics(bad));const s=emptyProgress();applyRace(s,race,days[0]);assert.deepEqual(s,emptyProgress());});
console.log(JSON.stringify({passed:true,checks},null,2));
