import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {emptyProgress,applyRace} from '../shared/progression.mjs';
const out='artifacts/progression-v1';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
const key='mushroom-driver-growth-v1-qa';
const release=async()=>{for(const k of ['KeyW','KeyS','KeyA','KeyD','Space'])await page.keyboard.up(k);};const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
async function follow(limit=100000){const end=Date.now()+limit;let samples=0;const laps=new Set();while(Date.now()<end){const d=await read();laps.add(d.lap);if(d.mode==='finished')return{finished:true,time:d.raceTime,samples,laps:[...laps],splits:d.trial.splits};const t=d.player.routeT+(9+Math.abs(d.player.speed)*.15)/d.trackLength;const p=await hook('trackPoint',t);const err=wrap(Math.atan2(p.x-d.player.x,p.z-d.player.z)-d.player.heading);await page.keyboard.up('KeyA');await page.keyboard.up('KeyD');if(Math.abs(err)>.05)await page.keyboard.down(err>0?'KeyA':'KeyD');if(Math.abs(err)>.5&&d.player.speed>30){await page.keyboard.up('KeyW');await page.keyboard.down('KeyS');}else{await page.keyboard.up('KeyS');await page.keyboard.down('KeyW');}samples++;await page.waitForTimeout(60);}return{finished:false,last:await read()};}
try{
 await page.goto('http://localhost:5173/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);
 await page.getByRole('button',{name:'每日挑战与车手成长'}).click();assert.equal(await page.locator('.growth-task').count(),3);assert.equal(await page.locator('.growth-reward button:disabled').count(),3);await page.screenshot({path:`${out}/desktop-challenges.png`});await page.keyboard.press('Escape');assert.equal((await read()).mode,'ready');checks.push('three daily objectives and three locked cosmetics are visible; Escape does not start race');
 await page.getByRole('button',{name:'计时挑战',exact:true}).click();await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');
 await page.getByRole('button',{name:'每日挑战与车手成长'}).click();const paused=(await read()).raceTime;await page.keyboard.press('KeyW');await page.waitForTimeout(150);assert.equal((await read()).raceTime,paused);await page.getByRole('button',{name:'关闭每日挑战'}).click();await page.click('#resume');
 const first=await follow();assert(first.finished,JSON.stringify(first));await release();assert.deepEqual(first.laps,[1,2,3]);assert.equal(first.splits.length,12);const earned=await hook('growth');assert(earned.snapshot.xp>=100);assert.equal(earned.metrics.rescues,0);assert.match(await page.locator('.growth-result').textContent(),/本场成长 \+\d+ XP/);await page.screenshot({path:`${out}/first-race-growth.png`});checks.push('real keyboard three-lap time trial earns XP, preserves 12 splits and growth dialog pauses input');
 await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);assert.equal((await hook('growth')).snapshot.xp,earned.snapshot.xp);
 await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');await page.keyboard.press('Escape');await page.click('#home');assert.equal((await hook('growth')).snapshot.xp,earned.snapshot.xp);checks.push('reload restores guest progress; abandoning race grants no XP');
 // Real pickup and rescue events after deterministic placement; no task state is injected.
 await hook('setState','active-play');await hook('setCoins',10);await hook('placeAtPickup','coin');await page.keyboard.down('KeyW');await page.waitForTimeout(150);await release();assert.equal((await hook('growth')).metrics.coinsCollected,1);assert.equal((await read()).coins,10);
 await page.keyboard.press('Backspace');await page.waitForTimeout(100);assert.equal((await hook('growth')).metrics.rescues,1);
 await hook('setupDetour','far');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.growth().metrics.rescues===2);checks.push('coin pickup counts at wallet cap; manual and automatic rescue each count once');
 await hook('setupCourse',{id:'garden',u:.84,speed:30,time:0});await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.growth().metrics.shortcutClears===1);await release();checks.push('crossing actual shortcut exit records challenge progress');
 // Existing driving controller holds an actual drift to orange, then releases it.
 await hook('setState','active-play');await page.keyboard.down('KeyW');await page.keyboard.down('KeyA');await page.keyboard.down('Space');await page.waitForTimeout(100);let maxCharge=0;const end=Date.now()+6500;
 while(Date.now()<end){const d=await read();maxCharge=Math.max(maxCharge,d.charge);if(d.player.driftStage>=2)break;const p=await hook('trackPoint',d.player.routeT+(9+Math.abs(d.player.speed)*.15)/d.trackLength);const err=wrap(Math.atan2(p.x-d.player.x,p.z-d.player.z)+.28-d.player.heading);await page.keyboard.up('KeyA');await page.keyboard.up('KeyD');await page.keyboard.down(err>.04?'KeyA':'KeyD');await page.waitForTimeout(60);}
 assert(maxCharge>=2.05,`actual drift charge ${maxCharge}`);await page.keyboard.up('Space');await page.waitForTimeout(60);assert.equal((await hook('growth')).metrics.orangeDrifts,1);await release();checks.push('real orange drift release increments task once');
 // Seed a valid prior-day guest history solely to inspect all unlocked reward surfaces.
 let mature=emptyProgress();for(const d of ['2026-01-01','2026-01-02'])mature=applyRace(mature,{mode:'time-trial',metrics:{orangeDrifts:3,coinsCollected:10,rescues:0,shortcutClears:2}},d);
 await page.evaluate(({key,value})=>localStorage.setItem(key,JSON.stringify(value)),{key,value:mature});await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);const colors=(await hook('growth')).paint;
 await page.getByRole('button',{name:'每日挑战与车手成长'}).click();for(const name of ['薄荷车漆','紫色尾焰','星光车手'])await page.getByRole('button',{name:`装备${name}`,exact:true}).click();await page.screenshot({path:`${out}/desktop-unlocked.png`});const styled=await hook('growth');assert.deepEqual(styled.equipped,{paint:'mint',trail:'violet',title:'star'});assert.notDeepEqual(styled.paint[0].colors,colors[0].colors);assert.deepEqual(styled.paint.slice(1),colors.slice(1));await page.getByRole('button',{name:'关闭每日挑战'}).click();await page.screenshot({path:`${out}/mint-kart.png`});
 await hook('selectDriver','luigi');const switched=await hook('growth');assert(switched.paint[0].colors.includes(0x47d9b1));assert.deepEqual(switched.paint.find(r=>r.key==='mario').colors,colors.find(r=>r.key==='mario').colors);checks.push('all three earned cosmetics equip; repaint affects only player and follows driver selection');
 await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);assert.equal((await hook('growth')).equipped.title,'star');await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/mobile-menu.png`});await page.getByRole('button',{name:'每日挑战与车手成长'}).click();await page.screenshot({path:`${out}/mobile-challenges.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.growth-dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false);for(const name of ['薄荷车漆','紫色尾焰','星光车手'])await page.getByRole('button',{name:`恢复默认${name}`,exact:true}).click();assert.deepEqual((await hook('growth')).equipped,{paint:'standard',trail:'standard',title:'rookie'});await page.getByRole('button',{name:'关闭每日挑战'}).click();
 await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');assert((await hook('racerPositions')).every(r=>r.visible));assert((await hook('pickups')).some(p=>p.kind==='item'&&p.visible));await page.screenshot({path:`${out}/mobile-racing.png`});checks.push('equipment persists and restores defaults; mobile dialog fits; Grand Prix traffic and items remain');
 assert.deepEqual(errors,[]);const report={passed:true,checks,first,earnedMetrics:earned.metrics,earnedXP:earned.snapshot.xp,maxCharge,errors};await fs.writeFile(`${out}/browser.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
