import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs/promises';
const out='artifacts/tactics-v1';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.__TACTICS_PAD__=[];Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[{id:'Standard test controller',index:0,connected:true,mapping:'standard',timestamp:performance.now(),axes:[0,0,0,0],buttons:Array.from({length:17},(_,i)=>({pressed:window.__TACTICS_PAD__.includes(i),touched:false,value:window.__TACTICS_PAD__.includes(i)?1:0}))}]});});
const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__),hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
async function frame(){const f=(await read()).frame;await page.waitForFunction(n=>window.__THREE_GAME_DIAGNOSTICS__.frame>n,f);}
async function fixture(arg={}){for(const key of ['KeyW','KeyS','KeyA','KeyD','Space','KeyC','KeyE'])await page.keyboard.up(key);await hook('tacticsFixture',arg);await frame();}
async function capture(name){await hook('setPausedForScreenshot',true);await page.screenshot({path:`${out}/${name}.png`});await hook('setPausedForScreenshot',false);}
async function use(item){await hook('giveItem',item);await frame();await page.keyboard.press('KeyE');await frame();}
async function steer(lane=0){const d=await read(),p=await hook('techniquePoint',{t:d.player.routeT+(8+Math.abs(d.player.speed)*.12)/d.trackLength,lane}),a=Math.atan2(p.x-d.player.x,p.z-d.player.z)-d.player.heading,e=Math.atan2(Math.sin(a),Math.cos(a));for(const [k,on]of[['KeyA',e>.035],['KeyD',e<-.035],['KeyW',true]]){await page.keyboard[on?'down':'up'](k);}await page.waitForTimeout(25);}
try{
 await page.goto((process.env.GAME_URL||'http://localhost:5180')+'/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);
 const belt=[];for(const lane of [5,-5,0]){await fixture({t:.33,lane,time:2});const initial=await read();await page.waitForFunction(t=>window.__THREE_GAME_DIAGNOSTICS__.raceTime>t+.6,initial.raceTime);const d=await read(),meters=(d.player.routeT-initial.player.routeT)*d.trackLength;belt.push({lane,meters});if(lane===0)assert(Math.abs(meters)<.1);else assert(Math.sign(meters)===Math.sign(lane)&&Math.abs(meters)>3);if(lane===5)await capture('belt-forward');}checks.push('parked kart is carried forward/backward by actual belts; central road stays still');
 await fixture({t:.19,lane:3.5,speed:28,time:2});const wetStart=(await read()).raceTime;let sawWet=false;while((await read()).raceTime<wetStart+1){await steer(3.5);sawWet||=(await read()).tactics.grip<.8;}assert(sawWet);assert.equal((await read()).player.recoveryFlash,0);await capture('wet-driving');checks.push('real steering traverses wet lane with reduced grip and no unexpected rescue');
 await fixture({t:.33,lane:5,time:10.2});await use('star');await hook('tacticsBomb',{distance:20});await page.keyboard.press('Escape');const paused=await hook('tactics'),clock=(await read()).raceTime;await page.waitForTimeout(350);assert.deepEqual(await hook('tactics'),paused);assert.equal((await read()).raceTime,clock);await page.click('#resume');await frame();assert((await hook('tactics')).stars.mario<paused.stars.mario);await capture('belt-warning');checks.push('real pause freezes belt phase, bomb fuse and star duration together');
 await fixture({t:.1,lane:0,time:2});await hook('giveItem','bomb');await hook('addReserve','banana');await frame();await page.keyboard.press('KeyE');await frame();let t=await hook('tactics'),d=await read();assert.equal(t.bombs.length,1);assert.equal(d.item,'banana');assert(t.bombs[0].velocity[0]*Math.sin(d.player.heading)+t.bombs[0].velocity[2]*Math.cos(d.player.heading)>0);await capture('bomb-fuse');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.tactics.stats.explosions===1);await page.waitForTimeout(250);assert.equal((await hook('tactics')).stats.explosions,1);checks.push('front throw consumes one slot, preserves reserve and explodes once after a visible fuse');
 await fixture({t:.1,lane:0,time:2});await page.keyboard.down('KeyC');await use('bomb');d=await read();t=await hook('tactics');assert(t.bombs[0].velocity[0]*Math.sin(d.player.heading)+t.bombs[0].velocity[2]*Math.cos(d.player.heading)<0);await page.keyboard.up('KeyC');checks.push('rear-view plus item places bomb behind using the same item controls');
 await fixture({t:.1,lane:0,time:2});await hook('tacticsBomb',{wall:true});assert.equal((await hook('tactics')).stats.bombHits,0);assert.equal((await hook('tactics')).stats.explosions,1);await hook('setPausedForScreenshot',false);checks.push('actual solid guardrail blocks blast damage');
 await fixture({t:.1,lane:0,time:2});await hook('tacticsBomb',{distance:5});await use('super-horn');assert.equal((await hook('tactics')).bombs.length,0);assert.equal((await hook('tactics')).stats.explosions,0);checks.push('super horn safely clears nearby bomb without triggering its blast');
 await fixture({t:.1,lane:0,time:2});await use('star');await hook('tacticsBomb',{age:2.15});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.tactics.stats.explosions===1);assert.equal((await read()).interactions.hits,0);const first=await hook('tacticsContact'),second=await hook('tacticsContact');assert(first.stun>0);assert.equal(second.hits,first.hits);await capture('star-protection');const deadline=Date.now()+12000;while((await hook('tactics')).stars.mario>0&&Date.now()<deadline)await steer(-3.5);await page.keyboard.up('KeyW');await hook('tacticsBomb',{age:2.15});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.interactions.hits===1);checks.push('star ignores bomb, hits each contacted rival once, and damage resumes after expiration');
 await fixture({t:.1,lane:0});await use('bomb');await page.keyboard.press('Escape');await page.click('#home');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='ready');assert.equal((await hook('tactics')).bombs.length,0);assert.deepEqual((await hook('tactics')).stars,{});assert(await page.locator('#tactics-hud').isHidden());
 await page.click('#loadout-open');const before=await page.evaluate(()=>({...localStorage}));await page.click('#tactics-practice');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');assert.equal((await read()).track,'castle');assert((await read()).practice);await hook('practiceNearEnd');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='finished');assert.deepEqual(await page.evaluate(()=>({...localStorage})),before);await page.click('#resume');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='countdown');assert.equal((await read()).track,'castle');await page.keyboard.press('Escape');await page.click('#home');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='ready'&&window.__THREE_GAME_DIAGNOSTICS__.track==='mushroom');await page.keyboard.press('Escape');assert.equal((await read()).track,'mushroom');checks.push('home clears tactical state; castle practice retries its track, writes no results and restores garage');
 for(const viewport of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(viewport);await fixture({t:.33,lane:5,time:10.1});await hook('giveItem','bomb');await frame();await page.locator('#item').tap();await frame();assert.equal((await hook('tactics')).stats.bombs,1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await capture(viewport.width===390?'mobile-tactics':'landscape-tactics');}checks.push('touch item use works in portrait/landscape with no horizontal overflow');
 for(const item of ['bomb','star']){await fixture({t:.1,lane:0,time:2});await hook('giveItem',item);await hook('addReserve','banana');await frame();await page.evaluate(()=>window.__TACTICS_PAD__=[4]);await page.waitForTimeout(350);const state=await hook('tactics');assert.equal(state.stats[item==='bomb'?'bombs':'stars'],1);assert.equal((await read()).item,'banana');await page.evaluate(()=>window.__TACTICS_PAD__=[]);await frame();assert.equal((await read()).item,'banana');}checks.push('standard gamepad shoulder uses bomb/star once per press and preserves reserve during long hold');
 assert.deepEqual(errors,[]);const report={passed:true,checks,belt,errors};await fs.writeFile(out+'/browser.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({error:String(e),checks,errors,last:await read()},null,2));await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
