import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/techniques-v1';const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
try{
 await page.goto('http://localhost:5173/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);
 const keys=await hook('loadout');assert.match(keys.ghostKey,/techniques1/);assert.match(keys.bestKey,/-v6-/);assert.match(keys.cupKey,/-v4-/);assert.match(keys.eliminationKey,/-v4-/);
 await page.click('#cup-select');await page.click('#start');await hook('cupNearFinish');await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='finished');await page.keyboard.up('KeyW');await page.click('#resume');
 await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.track==='castle');assert.deepEqual((await hook('techniques')).ramps,[]);assert.equal((await hook('techniques')).ramp.height,0);assert.equal((await hook('techniques')).stats.jumps,0);await page.keyboard.press('Escape');await page.click('#home');assert.equal((await hook('techniques')).ramps.length,2);checks.push('cup switches to castle with no carried ramp/flight; home restores mushroom ramps');
 await page.click('#elimination-select');await page.click('#loadout-open');const before=await page.evaluate(()=>({...localStorage}));await page.click('#loadout-test-drive');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');await hook('practiceNearEnd');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='finished');assert.deepEqual(await page.evaluate(()=>({...localStorage})),before);await page.click('#home');await page.keyboard.press('Escape');assert.equal((await hook('eliminationState')).selected,true);assert.equal((await hook('techniques')).stats.jumps,0);checks.push('practice writes no records and returns to selected elimination mode');
 await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');await hook('eliminationFixture',{time:25,playerLast:true});await hook('eliminationTick',30);assert.equal((await hook('eliminationState')).state.complete,true);await hook('setPausedForScreenshot',false);await page.click('#resume');assert.equal((await hook('eliminationState')).lapLimit,null);assert.equal((await hook('techniques')).draft.charge,0);assert.equal((await hook('techniques')).ramp.height,0);checks.push('elimination loss/retry restores six racers and clears draft/flight without a lap limit');
 assert.deepEqual(errors,[]);const result={passed:true,method:'QA boundary fixtures for lifecycle transitions; full racing covered separately.',checks,errors};await fs.writeFile(out+'/modes.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
