import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/techniques-v1';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__),hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
const release=async()=>{for(const key of ['KeyW','KeyS','KeyA','KeyD','Space','KeyE'])await page.keyboard.up(key);};
async function steer(lane=3.5){const d=await read(),p=await hook('techniquePoint',{t:d.player.routeT+(7+Math.abs(d.player.speed)*.12)/d.trackLength,lane}),a=Math.atan2(p.x-d.player.x,p.z-d.player.z)-d.player.heading,e=Math.atan2(Math.sin(a),Math.cos(a));await page.keyboard.up('KeyA');await page.keyboard.up('KeyD');if(Math.abs(e)>.035)await page.keyboard.down(e>0?'KeyA':'KeyD');}
async function ramps({jump=true,lane=3.5,capture=false}={}){
 await release();await hook('techniqueFixture',{kind:'ramp',lane,speed:40});await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.techniques.jumps===0&&window.__THREE_GAME_DIAGNOSTICS__.player.routeT<.72);await page.keyboard.down('KeyW');let air=0,peak=0,groundHazard=false,pauseChecked=false;const deadline=Date.now()+15000;
 while(Date.now()<deadline){const d=await read();if(d.player.routeT>.84&&!d.techniques.ramp.airborne)break;const r=d.techniques.ramp;peak=Math.max(peak,r.height);if(r.airborne)air++;
  if(capture&&r.height>.8&&!r.airborne&&!pauseChecked){await hook('setPausedForScreenshot',true);await page.screenshot({path:out+'/ramp-approach.png'});await hook('setPausedForScreenshot',false);}
  if(jump&&r.trickReady&&!r.trick)await page.keyboard.down('Space');else if(!r.trickReady)await page.keyboard.up('Space');
  if(capture&&r.airborne&&r.height>1.6&&!groundHazard){await hook('techniqueHazard');groundHazard=true;await hook('setPausedForScreenshot',true);await page.screenshot({path:out+'/ramp-air.png'});await hook('setPausedForScreenshot',false);await page.keyboard.press('Escape');const before=await read();await page.waitForTimeout(150);assert.equal((await read()).raceTime,before.raceTime);assert.equal((await read()).techniques.ramp.height,before.techniques.ramp.height);await page.click('#resume');await page.keyboard.down('KeyW');pauseChecked=true;}
  await steer(lane);await page.waitForTimeout(35);
 }
 await release();return {last:await read(),peak,air,pauseChecked};
}
try{
 await page.goto('http://localhost:5173/?test=1&v=techniques-v1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);
 const good=await ramps({capture:true});assert.equal(good.last.techniques.jumps,2,JSON.stringify(good));assert(good.peak>1.8);assert(good.pauseChecked);assert.equal(good.last.interactions.hits,0);assert.equal(good.last.player.recoveryFlash,0);await page.screenshot({path:out+'/ramp-landing.png'});checks.push('real keyboard drives two ramps with timed tricks; pause freezes flight and ground banana does not hit airborne kart');
 const missed=await ramps({jump:false});assert.equal(missed.last.techniques.jumps,0);assert(missed.peak>1.8);const bypass=await ramps({lane:-3,jump:false});assert.equal(bypass.peak,0);assert.equal(bypass.last.techniques.jumps,0);checks.push('missing trick still lands; optional left ground lane bypasses both ramps');
 await hook('techniqueFixture',{kind:'horn',speed:0});await page.waitForTimeout(60);await hook('giveItem','triple-mushroom');await hook('addReserve','banana');
 for(const left of [2,1,0]){await page.keyboard.press('KeyE');await page.waitForTimeout(50);assert((await read()).boost>0);assert.equal((await read()).item,left?'triple-mushroom':'banana');if(left)assert.equal((await read()).inventory[0].charges,left);}
 await page.keyboard.down('KeyE');await page.waitForTimeout(280);assert.equal((await hook('combat')).held,'banana');await page.keyboard.press('Escape');assert.equal((await hook('combat')).held,null);assert.equal((await read()).item,'banana');await page.keyboard.up('KeyE');await page.click('#resume');checks.push('three presses consume one triple slot and retain backup; normal held defense still cancels safely on pause');
 await hook('techniqueFixture',{kind:'horn',speed:0});await page.waitForTimeout(70);await hook('giveItem','super-horn');await hook('attack',{kind:'red-shell',rear:true});await page.keyboard.press('KeyE');await page.waitForTimeout(70);assert.equal((await read()).techniques.horns,1);assert((await read()).techniques.hornClears>=1);assert((await hook('racerPositions'))[1].hitTime>0);assert((await hook('hornWallFixture')).remaining);checks.push('horn clears an actual incoming red shell, hits nearby rival and cannot clear through guardrail');
 await hook('techniqueFixture',{kind:'horn',speed:0});await page.waitForTimeout(50);await page.keyboard.press('Backspace');await page.waitForTimeout(720);const hits=(await read()).interactions.hits;await hook('attack',{kind:'super-horn'});await page.waitForTimeout(50);assert.equal((await read()).interactions.hits,hits);checks.push('horn respects rescue protection after stun ends');
 await hook('techniqueFixture',{kind:'draft',speed:35});await page.keyboard.down('KeyW');const deadline=Date.now()+4000;while(Date.now()<deadline&&(await read()).techniques.drafts===0){const state=await hook('techniques');await steer(state.ai[0].lane);await page.waitForTimeout(35);}await release();assert((await read()).techniques.drafts>0,JSON.stringify(await read()));checks.push('sustained real follow grants a draft boost');
 await page.setViewportSize({width:390,height:844});await hook('techniqueFixture',{kind:'horn',speed:0});await page.waitForTimeout(60);await hook('giveItem','triple-mushroom');await page.locator('#item').tap();await page.waitForTimeout(50);assert.equal((await read()).inventory[0].charges,2);await page.screenshot({path:out+'/mobile-items.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await hook('techniqueFixture',{kind:'ramp',lane:3.5,speed:0});const touch=await page.locator('[data-key=ArrowUp]').boundingBox(),cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touch.x+touch.width/2,y:touch.y+touch.height/2}]});await page.waitForTimeout(350);assert((await read()).player.speed>10);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await page.waitForTimeout(80);await page.setViewportSize({width:844,height:390});await page.screenshot({path:out+'/landscape.png'});checks.push('mobile uses triple item and real throttle/cancel; portrait and landscape fit');
 await hook('setState','ready');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='ready');assert.equal((await hook('techniques')).stats.jumps,0);assert.equal((await hook('techniques')).ramp.height,0);assert.equal((await hook('techniques')).draft.charge,0);assert.deepEqual(errors,[]);
 const report={passed:true,checks,errors};await fs.writeFile(out+'/browser.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({checks,errors,last:await read(),techniques:await hook('techniques')},null,2));await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
