import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/time-trial-v1';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg});
const key='mushroom-time-trial-ghost-v1-course2-handling1-techniques1-tactics1-light-qa';
const release=async()=>{for(const k of ['KeyW','KeyS','KeyA','KeyD','Space'])await page.keyboard.up(k);};const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
async function follow(limit=100000){const end=Date.now()+limit;let samples=0;const laps=new Set();while(Date.now()<end){const d=await read();laps.add(d.lap);if(d.mode==='finished')return{finished:true,time:d.raceTime,samples,laps:[...laps],splits:d.trial.splits};const t=d.player.routeT+(9+Math.abs(d.player.speed)*.15)/d.trackLength;const p=await hook('trackPoint',t);const err=wrap(Math.atan2(p.x-d.player.x,p.z-d.player.z)-d.player.heading);await page.keyboard.up('KeyA');await page.keyboard.up('KeyD');if(Math.abs(err)>.05)await page.keyboard.down(err>0?'KeyA':'KeyD');if(Math.abs(err)>.5&&d.player.speed>30){await page.keyboard.up('KeyW');await page.keyboard.down('KeyS');}else{await page.keyboard.up('KeyS');await page.keyboard.down('KeyW');}samples++;await page.waitForTimeout(60);}return{finished:false,last:await read()};}
try{
 await page.goto('http://localhost:5173/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__);await page.evaluate(key=>localStorage.removeItem(key),key);await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);
 await page.getByRole('button',{name:'计时挑战',exact:true}).click();assert.equal(await page.locator('[data-race-mode=time-trial]').getAttribute('aria-pressed'),'true');await page.screenshot({path:`${out}/mode-menu.png`});
 await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');assert.equal((await read()).raceMode,'time-trial');assert((await hook('racerPositions')).filter(r=>r.key!=='mario').every(r=>!r.visible));assert((await hook('pickups')).filter(p=>p.kind==='item').every(p=>!p.visible));await page.keyboard.press('KeyE');assert.equal((await read()).projectiles.length,0);checks.push('time trial has no AI traffic, random boxes or item actions');
 const first=await follow();assert(first.finished,JSON.stringify(first));assert.equal(first.splits.length,12);assert.deepEqual(first.laps,[1,2,3]);await release();const stored=await page.evaluate(key=>localStorage.getItem(key),key);assert(stored);const run=JSON.parse(stored);assert(run.frames.length>800);assert.equal(run.frames[0][0],0);assert.equal(run.frames.at(-1)[0],run.durationMs);assert.equal(run.splits.at(-1),run.durationMs);assert.equal(run.character,'mario');assert.match(await page.locator('#dialog-title').textContent(),/首个计时纪录/);await page.screenshot({path:`${out}/first-finish.png`});checks.push('real keyboard three-lap run records 12 splits and persists a complete first ghost');
 await page.click('#resume');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');await page.waitForTimeout(800);assert((await read()).trial.ghostVisible);const before=await read();assert.equal(before.player.speed,0);await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='paused');const paused=await read();await page.waitForTimeout(300);assert.deepEqual((await read()).trial.ghostPosition,paused.trial.ghostPosition);assert.equal((await read()).raceTime,paused.raceTime);await page.click('#resume');await page.waitForTimeout(900);await page.screenshot({path:`${out}/ghost-chase.png`});await page.click('#ghost-toggle');await page.waitForTimeout(50);assert.equal((await read()).trial.ghostVisible,false);await page.click('#ghost-toggle');checks.push('ghost replays on retry, freezes on pause, toggles visibility and never pushes stopped player');
 const second=await follow();assert(second.finished,JSON.stringify(second));await release();assert(second.time>first.time);assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),stored);assert.equal(second.splits.length,12);assert.equal(await page.locator('.trial-results tbody tr').count(),12);assert.match(await page.locator('.trial-summary').textContent(),/慢/);await page.screenshot({path:`${out}/second-finish-splits.png`});checks.push('slower full run shows 12 comparisons and keeps the faster stored ghost');
 await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);await page.getByRole('button',{name:'计时挑战',exact:true}).click();assert.equal((await hook('ghostData')).durationMs,run.durationMs);checks.push('reload restores valid best replay');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/mobile-mode-menu.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');await page.waitForTimeout(900);await page.screenshot({path:`${out}/mobile-ghost.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('mobile mode picker, trial HUD and ghost fit viewport');
 await page.keyboard.press('Escape');await page.click('#home');await page.getByRole('button',{name:'道具竞速',exact:true}).click();await page.click('#start');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.mode==='racing');assert.equal((await read()).trial.ghostVisible,false);assert((await hook('racerPositions')).every(r=>r.visible));assert((await hook('pickups')).some(p=>p.kind==='item'&&p.visible));checks.push('switching back restores AI and boxes without a ghost');
 assert.deepEqual(errors,[]);const report={passed:true,checks,first,second,frames:run.frames.length,bytes:stored.length,errors};await fs.writeFile(`${out}/browser.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
