import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/tricks-v1';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const hook=(name,arg)=>page.evaluate(({name,arg})=>window.__THREE_GAME_TEST_HOOKS__[name](arg),{name,arg}),read=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__),score=()=>hook('tricks');
const release=async()=>{for(const k of ['KeyW','KeyS','KeyA','KeyD','Space'])await page.keyboard.up(k);};const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const reset=async()=>{await release();await hook('setupTrickPass');await page.waitForTimeout(60);};
async function followRoute(route){const end=Date.now()+20000;while(Date.now()<end){const d=await read(),u=(d.player.routeT-route.from)/(route.to-route.from);if(u>=1.005)return true;const targetU=u+(10+Math.abs(d.player.speed)*.16)/route.length,lane=targetU>.29&&targetU<.70?(route.id==='garden'?-2:-2.6):0;const p=targetU<1?await hook('coursePoint',{id:route.id,u:Math.max(0,targetU),lane}):await hook('trackPoint',route.to+(targetU-1)*route.length/d.trackLength);const e=wrap(Math.atan2(p.x-d.player.x,p.z-d.player.z)-d.player.heading);await page.keyboard.up('KeyA');await page.keyboard.up('KeyD');if(Math.abs(e)>.035)await page.keyboard.down(e>0?'KeyA':'KeyD');if(Math.abs(e)>.3&&d.player.speed>28){await page.keyboard.up('KeyW');await page.keyboard.down('KeyS');}else{await page.keyboard.up('KeyS');await page.keyboard.down('KeyW');}await page.waitForTimeout(50);}return false;}
try{
 await page.goto('http://localhost:5173/?test=1');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);assert.equal(await page.locator('#trick-hud').isVisible(),false);
 await reset();await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.tricks().counts.overtake===1,null,{timeout:5000});assert.equal((await score()).score,120);await page.screenshot({path:out+'/close-overtake.png'});checks.push('real throttle passes a nearby moving rival and awards 120 points');
 await reset();for(const [stage,kind] of [[2,'orange'],[3,'purple']]){await hook('prepareTrickTurbo',stage);await page.keyboard.down('Space');await page.keyboard.up('Space');await page.waitForFunction(kind=>window.__THREE_GAME_TEST_HOOKS__.tricks().counts[kind]===1,kind);assert((await read()).boost>0);}assert.equal((await score()).score,370);checks.push('actual drift release at orange/purple thresholds awards one event each; purple is not double-counted');
 await hook('trickDemo');const demo=await score();assert.equal(demo.multiplier,3);await page.keyboard.press('Escape');const paused=await score();await page.waitForTimeout(300);assert.deepEqual(await score(),paused);await page.click('#resume');await page.waitForTimeout(80);assert((await score()).remaining<paused.remaining);checks.push('combo caps at 3x and simulation countdown freezes across pause');
 await hook('trickDemo');const beforeCrash=(await score()).score;await hook('placeAtBarrier',true);await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__.tricks().chain===0);assert.equal((await score()).score,beforeCrash);assert.match((await score()).breakReason,/重撞/);checks.push('real boosted guardrail impact breaks combo while retaining earned points');
 await reset();await hook('trickDemo');const beforeRescue=(await score()).score;await page.keyboard.press('Backspace');await page.waitForTimeout(70);assert.equal((await score()).chain,0);assert.equal((await score()).score,beforeRescue);assert.match((await score()).breakReason,/救援/);checks.push('manual rescue breaks combo and keeps total');
 await reset();await hook('trickDemo');await hook('placeHazard','green-shell');await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.interactions.hits===1);assert.equal((await score()).chain,0);checks.push('real item damage breaks combo');
 await release();await hook('setState','ready');await hook('selectRaceMode','time-trial');const routes=await hook('courseInfo');for(const route of routes){await release();await hook('setupCourse',{id:route.id,u:0,speed:30,time:route.id==='workshop'?5:0});assert(await followRoute(route));assert.equal((await score()).counts.shortcut,1,JSON.stringify(await score()));assert.equal((await score()).counts.overtake,0);await release();}checks.push('real steering traverses both complete shortcuts and scores once in time trial without AI points');
 await hook('setupCourse',{id:'garden',u:.84,speed:30,time:0});await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.course.clears===1);assert.equal((await score()).counts.shortcut,0);checks.push('cutting into shortcut at the exit earns no trick points');
 await reset();await hook('trickDemo');await release();await hook('setPausedForScreenshot',true);await page.screenshot({path:out+'/desktop-combo.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/mobile-combo.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const b=await page.locator('#trick-hud').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=390);await hook('setPausedForScreenshot',false);
 const key=(await score()).key;await page.evaluate(key=>localStorage.removeItem(key),key);await hook('finishTrickFixture');await page.screenshot({path:out+'/mobile-results.png'});const completed=await score();assert.equal(Number(await page.evaluate(key=>localStorage.getItem(key),key)),completed.score);await page.locator('#resume').scrollIntoViewIfNeeded();await page.click('#resume');assert.equal((await score()).score,0);assert.equal((await score()).best,completed.score);checks.push('completion fixture persists best and mobile result retry remains reachable/resettable');
 await hook('setState','ready');await hook('selectDifficulty','casual');assert.notEqual((await score()).key,key);await hook('selectRaceMode','time-trial');assert.notEqual((await score()).key,key);await page.reload();await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__?.frame>3);assert.equal((await score()).best,completed.score);checks.push('mode/difficulty records are separated and reload restores best');
 assert.deepEqual(errors,[]);await fs.writeFile(out+'/browser.json',JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({checks,errors,last:await read(),tricks:await score()},null,2));await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
